apiVersion: v2
name: sample-app
description: A sample Helm chart for Kubernetes
type: application
version: 0.2.1
appVersion: "1.27.4"
maintainers:
  - name: xin
    email: aehrt55@aehrt55.net
home: https://github.com/marxbiotech/helm-charts
sources:
  - https://github.com/marxbiotech/helm-charts
